### ISSUE TITLE
CLASE 4 (JAVA) - Sobreescritura, Polimorfismo y instanceofLección

### ISSUE THREAD

**Issue by eugenia1984** [CodeSystem2022/ERROR-404-PROGRAMACION3#7]
- Para subir la clase 4 de Java.

- Temas: [Sobreescritura, Polimorfismo y instanceofLección](http://campus.frsr.utn.edu.ar/moodle/mod/lesson/view.php?id=33650)

**Comment by brianahumada** [comment]
Voy a subir la clase 4 de java

**Comment by eugenia1984** [comment]
Ya se unio a main
